services:
  web:
    image: ebota/daw:apache_php_mysql_mongodb
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    environment:
      MONGODB_URI: "mongodb://root:example@mongo:27017/admin"
    depends_on:
      - db
      - mongo

  db:
    image: mysql:9.3
    environment:
      MYSQL_ROOT_PASSWORD: passwordDeRootQueNoShaDeFerServirMai
      MYSQL_USER: usuari
      MYSQL_PASSWORD: paraula_de_pas
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo

volumes:
  mongodb_data: