SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS incidencies
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON incidencies.* TO 'usuari'@'%';
FLUSH PRIVILEGES;
USE incidencies;

CREATE TABLE TIPO(
    idTipo INT(11) AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(200) NOT NULL
);
CREATE TABLE DEPARTMENT(
    idDepartment INT(11) AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(200) NOT NULL
);
CREATE TABLE TECNIC(
    idTecnic INT(11) AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(200) NOT NULL
);
CREATE TABLE INCIDENCIA(
    idIncidencia INT(11) AUTO_INCREMENT PRIMARY KEY,
    descripcio VARCHAR(2000) NOT NULL,
    data TIMESTAMP NOT NULL,
    departament INT(11) NOT NULL,
    tecnic INT(11) NOT NULL,
    tipo INT(11) NOT NULL,
    dataFinalitzacio TIMESTAMP,
    prioritat ENUM('Alta', 'Mitja', 'Baixa') NOT NULL,
    FOREIGN KEY (tecnic) REFERENCES TECNIC(idTecnic),
    FOREIGN KEY (tipo) REFERENCES TIPO(idTipo),
    FOREIGN KEY (departament) REFERENCES DEPARTMENT(idDepartment)
);
CREATE TABLE ACTUACIO(
    idActuacio INT(11) AUTO_INCREMENT PRIMARY KEY,
    descripcio VARCHAR(2000) NOT NULL,
    data TIMESTAMP NOT NULL,
    temps INT(11) NOT NULL,
    incidencia INT(11) NOT NULL,
    visible INT(1) NOT NULL,
    FOREIGN KEY(incidencia) REFERENCES INCIDENCIA(idIncidencia)
);